/**
 * Dominio de Retail / Preventas — errores de dominio con `code` estable. PURO. NO se depende de mensajes
 * de Prisma como contrato: los conflictos de base (P2002/P2003) se TRADUCEN a estos códigos en la infra.
 */
export const RETAIL_ERROR = {
  CAMPAIGN_NOT_FOUND: "CAMPAIGN_NOT_FOUND",
  CAMPAIGN_NOT_EDITABLE: "CAMPAIGN_NOT_EDITABLE",
  INVALID_CAMPAIGN_TRANSITION: "INVALID_CAMPAIGN_TRANSITION",
  CAMPAIGN_NOT_OPEN: "CAMPAIGN_NOT_OPEN",
  CAMPAIGN_HAS_NO_OFFERS: "CAMPAIGN_HAS_NO_OFFERS",
  OFFER_ALREADY_EXISTS: "OFFER_ALREADY_EXISTS",
  OFFER_NOT_FOUND: "OFFER_NOT_FOUND",
  OFFER_NOT_EDITABLE: "OFFER_NOT_EDITABLE",
  INVALID_PRICE: "INVALID_PRICE",
  INVALID_DATES: "INVALID_DATES",
  INVALID_TITLE: "INVALID_TITLE",
  VOLUME_NOT_FOUND: "VOLUME_NOT_FOUND",
  STORE_COMMERCE_DISABLED: "STORE_COMMERCE_DISABLED",
  // Slice 3 — Reservas / StoreOrder
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_ACCESS_DENIED: "ORDER_ACCESS_DENIED",
  ORDER_ALREADY_EXISTS: "ORDER_ALREADY_EXISTS",
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  EMPTY_ORDER: "EMPTY_ORDER",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  TOO_MANY_ITEMS: "TOO_MANY_ITEMS",
  OFFER_NOT_AVAILABLE: "OFFER_NOT_AVAILABLE",
  OFFER_CAMPAIGN_MISMATCH: "OFFER_CAMPAIGN_MISMATCH",
  ORDER_TOTAL_MISMATCH: "ORDER_TOTAL_MISMATCH",
  // Slice 4 — Cumplimiento (operación de proveedor y llegada por línea)
  ORDER_LINE_NOT_FOUND: "ORDER_LINE_NOT_FOUND",
  ORDER_LINE_OPERATION_NOT_ALLOWED: "ORDER_LINE_OPERATION_NOT_ALLOWED",
  INVALID_FULFILLMENT_QUANTITY: "INVALID_FULFILLMENT_QUANTITY",
  NOTHING_PENDING: "NOTHING_PENDING",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_FULFILLMENT_STARTED: "ORDER_FULFILLMENT_STARTED",
  CAMPAIGN_HAS_ACTIVE_ORDERS: "CAMPAIGN_HAS_ACTIVE_ORDERS",
  OPERATION_KEY_CONFLICT: "OPERATION_KEY_CONFLICT",
  // Slice 5 — Avisos de llegada al cliente
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_ACCESS_DENIED: "NOTIFICATION_ACCESS_DENIED",
  NOTIFICATION_NOT_EDITABLE: "NOTIFICATION_NOT_EDITABLE",
  NOTIFICATION_ALREADY_SENT: "NOTIFICATION_ALREADY_SENT",
  NOTIFICATION_OPERATION_KEY_CONFLICT: "NOTIFICATION_OPERATION_KEY_CONFLICT",
  EMPTY_NOTIFICATION: "EMPTY_NOTIFICATION",
  INVALID_NOTIFICATION_QUANTITY: "INVALID_NOTIFICATION_QUANTITY",
  ARRIVAL_ALREADY_NOTIFIED: "ARRIVAL_ALREADY_NOTIFIED",
  ARRIVAL_NOTIFICATION_EXCEEDS_PENDING: "ARRIVAL_NOTIFICATION_EXCEEDS_PENDING",
} as const;
export type RetailErrorCode = (typeof RETAIL_ERROR)[keyof typeof RETAIL_ERROR];

export class RetailError extends Error {
  constructor(readonly code: RetailErrorCode, message?: string) {
    super(message ?? `retail: ${code}`);
    this.name = "RetailError";
  }
}
